### ISSUE TITLE
有没有类似于extjs中boder布局

### ISSUE THREAD

**Issue by hadoop835** [chuchur/kui-vue#1]

**Comment by chuchur** [comment]
可以大概说下具体需求吗，可以实现

**Comment by hadoop835** [comment]
可以将页面分隔为west,east,south,north,center。并且表格可以自适应center布局。

**Comment by chuchur** [comment]
这个可以有，做好了放上来

**Comment by chuchur** [comment]
加了布局组件Layout 基本满足了 demo ：https://k-ui.xyz/layout
