### ISSUE TITLE
理直气壮的撞库盗号刷星并且臭不要脸是一种怎样的体验？

### ISSUE THREAD

**Issue by broadliyn** [chuchur/kui-vue#11]
人品这么差，心思都花到刷星上了，那肯定项目质量堪忧了。

**Comment by zhangferry** [comment]
刷星不能代表人品差啊，也不能代表项目质量堪忧啊，但是却能十分准确地代表这个人很low

**Comment by chuchur** [comment]
你们开心就好哈

**Comment by YUFENGWANG** [comment]
为什么变成200多star了


淘宝退货了？

**Comment by yanhaijing** [comment]
https://weibo.com/githubchina
项目推广可以联系我哈，O(∩_∩)O哈哈~
