### ISSUE TITLE
Does support SSR？

### ISSUE THREAD

**Issue by kingszhai** [chuchur/kui-vue#20]
I use like this :
```js
//   /plugins/kui.js
import Vue from 'vue';
import kui from 'kui-vue';

Vue.use(kui);
import 'kui-vue/dist/k-ui.css';

//in nuxt.config.js
module.exports = {
    plugins: [ { src: '~plugins/kui', ssr: true }],
}
```
But error:
![image](https://user-images.githubusercontent.com/7829764/46243163-9cd5bf80-c403-11e8-9227-3bd50bb1026e.png)

What should I am going to do?

**Comment by chuchur** [comment]
It will be supported in the next version.
Thank you for your support.😊
