### ISSUE TITLE
Cannot declare a let variable twice: ‘e’

### ISSUE THREAD

**Issue by yingzaizai** [chuchur/kui-vue#22]
Error: SyntaxError: Cannot declare a let variable twice: 'e'.

Affected Versions: iOS 10.3, 10.1 devices/simulators

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/28983399/46251904-7b6fe480-c492-11e8-8a40-0b32216eb29b.png">

**Comment by chuchur** [comment]
是有这个问题，已经修复了，谢谢支持
