### ISSUE TITLE
在哪买的star啊？求店铺地址 Where did you buy star?

### ISSUE THREAD

**Issue by kaeyleo** [chuchur/kui-vue#6]

**Comment by Dcatfly** [comment]
怎么还自带翻译呢。。😂
[V站讨论贴](https://www.v2ex.com/t/485555#reply51)

**Comment by xbb2yy** [comment]
这个花费不小啊

**Comment by youzizi1** [comment]
哎~

**Comment by int64ago** [comment]
可耻

**Comment by yanhaijing** [comment]
@kaeyleo 可以联系我哈，O(∩_∩)O哈哈~

**Comment by yanhaijing** [comment]
@kaeyleo 可以联系我哈，O(∩_∩)O哈哈~

**Comment by int64ago** [comment]
删是删不了的

![image](https://user-images.githubusercontent.com/2230882/45013158-ac542980-b04c-11e8-867d-008d42be54b5.png)

![image](https://user-images.githubusercontent.com/2230882/45013161-afe7b080-b04c-11e8-82b2-f94e85d6bbb5.png)

**Comment by chuchur** [comment]
没有什么店铺，就跑了个脚本，别跟着起哄哈。
